import { Injectable } from '@angular/core';
import { GenerosService, modeloGenero } from '../generos/generos.service';

export interface modeloPublicacao {
  idPublicacao: number,
  idAutorPublicacao: number,
  tituloPublicacao: string,
  descricaoPublicacao: string,
  generoPublicacao: modeloGenero,
  faixaEtariaPublicacao: string,
  pesoPublicacao: number,
  tamPublicacao: number[],
  qtdPaginasPublicacao: number,
  precoDePublicacao: number,
  precoPorPublicacao: number,
  fotosPublicacao: Object[]
}

@Injectable({
  providedIn: 'root'
})
export class PublicacoesService {

  constructor() { }

  static publicacoesCadastradas: modeloPublicacao[] = [
    { idPublicacao: 1, idAutorPublicacao: 1, tituloPublicacao: 'Meninos e Dragões', descricaoPublicacao: "Em um mundo de magia, tecnologia e dragões, acompanhe as aventuras de Rodrigo, Tobias e da princesa Amanda, tentando salvar seu novo amigo, o simpático dragão Foguinho, do maior caçador de dragões de todos os tempos. Esse livro marca um novo começo para a série “Meninos e Dragões”, vencedora do Prêmio Angelo Agostini.", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+10', pesoPublicacao: 300, tamPublicacao: [17, 24], qtdPaginasPublicacao: 56, precoDePublicacao: 39.00, precoPorPublicacao: 29.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao1.jpg'] },
    { idPublicacao: 2, idAutorPublicacao: 1, tituloPublicacao: 'Coelho Nero', descricaoPublicacao: "Mal-humorado, ranzinza, de temperamento ácido e crítico, o Coelho Nero, personagem criado pelo desenhista Omar Viñole, ganha sua segunda coletânea impressa: Simpático – Só que não. Assim como a primeira, lançada em 2013, a coletânea apresente 48 tiras (a maioria foi publicada no blog do personagem) e material inédito, produzido para esta edição.", generoPublicacao: GenerosService.generosCadastrados[7], faixaEtariaPublicacao: '+16', pesoPublicacao: 100, tamPublicacao: [14, 21], qtdPaginasPublicacao: 16, precoDePublicacao: 15.00, precoPorPublicacao: 5.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao2.jpg'] },
    { idPublicacao: 3, idAutorPublicacao: 1, tituloPublicacao: 'Orixás: do Orum ao AyÊ', descricaoPublicacao: "O álbum Orixás – Do Orum ao Ayê é dividido em cinco capítulos recheados de narrativas arrojadas e traz ao público geral histórias que apenas eram partilhadas por quem frequenta os lugares sagrados em que se cultuam os orixás. Os autores usaram de uma linguagem poderosa, apontando para uma nova geração de leitores, dos que creem e os que apenas querem inteirar-se da concepção de mundo dos que seguem os preceitos do candomblé, para reproduzir histórias fascinantes e encantadoras.", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+10', pesoPublicacao: 350, tamPublicacao: [17, 26], qtdPaginasPublicacao: 80, precoDePublicacao: 40, precoPorPublicacao: 30,fotosPublicacao: ['../assets/publicacoes/default/publicacao3.jpg'] },
    { idPublicacao: 4, idAutorPublicacao: 1, tituloPublicacao: 'Omar Viñole - Sketchboo Custom', descricaoPublicacao: "O Omar Vinõle – SKETCHBOOK CUSTOM Volume 1 apresenta o trabalho do artista com esboços e artes-finais em vários estágios, estilos e técnicas, tiradas de seu acervo pessoal, num flagrante não convencional de sua produção ao longo da carreira.", generoPublicacao: GenerosService.generosCadastrados[1], faixaEtariaPublicacao: '+16', pesoPublicacao: 300, tamPublicacao: [21, 28], qtdPaginasPublicacao: 64, precoDePublicacao: 49.90, precoPorPublicacao: 39.90, fotosPublicacao: ['../assets/publicacoes/default/publicacao4.jpg'] },
    { idPublicacao: 5, idAutorPublicacao: 1, tituloPublicacao: 'Aura', descricaoPublicacao: "Aura, nova HQ que é um spin-off de Volkan, lançada no ano passado. Criada por Allan Albuquerque, Aura tem desenhos de Omar Viñole, esboços de Caio Majado, cores de Marco Pelandra e capa de Netho Dias. Todos nós, independente da idade ou do estilo de vida que levamos, passamos por grandes desafios na vida, e diante disso, cada um encara esses momentos de diferentes maneiras. Com Fernanda não é diferente. Ela é uma jovem da zona leste de São Paulo, que passa por problemas semelhantes ou piores aos nossos, porém, a sua maneira de enfrentá-los é bastante incomum.", generoPublicacao: GenerosService.generosCadastrados[7], faixaEtariaPublicacao: '+10', pesoPublicacao: 150, tamPublicacao: [26, 34], qtdPaginasPublicacao: 24, precoDePublicacao: 50.00, precoPorPublicacao: 20.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao5.jpg'] },
    { idPublicacao: 6, idAutorPublicacao: 1, tituloPublicacao: 'Histórias Passageiras', descricaoPublicacao: "", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+16', pesoPublicacao: 125, tamPublicacao: [12, 15], qtdPaginasPublicacao: 80, precoDePublicacao: 55.00, precoPorPublicacao: 35.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao6.jpg'] },
    { idPublicacao: 7, idAutorPublicacao: 1, tituloPublicacao: 'Volkan 01', descricaoPublicacao: "", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+12', pesoPublicacao: 105, tamPublicacao: [12, 15], qtdPaginasPublicacao: 70, precoDePublicacao: 45.00, precoPorPublicacao: 20.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao7.jpg'] },
    { idPublicacao: 8, idAutorPublicacao: 1, tituloPublicacao: 'Volkan 02', descricaoPublicacao: "", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+12', pesoPublicacao: 115, tamPublicacao: [12, 15], qtdPaginasPublicacao: 80, precoDePublicacao: 35.00, precoPorPublicacao: 20.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao8.jpg'] },
    { idPublicacao: 9, idAutorPublicacao: 1, tituloPublicacao: 'Orixás - em Guerra', descricaoPublicacao: "", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+16', pesoPublicacao: 125, tamPublicacao: [12, 15], qtdPaginasPublicacao: 60, precoDePublicacao: 35.00, precoPorPublicacao: 25.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao9.jpg'] },
    { idPublicacao: 10, idAutorPublicacao: 1, tituloPublicacao: 'O Alienista - Em Quadrinhos', descricaoPublicacao: "", generoPublicacao: GenerosService.generosCadastrados[7], faixaEtariaPublicacao: '+16', pesoPublicacao: 135, tamPublicacao: [12, 15], qtdPaginasPublicacao: 50, precoDePublicacao: 15.00, precoPorPublicacao: 10.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao10.jpg'] },
    { idPublicacao: 11, idAutorPublicacao: 2, tituloPublicacao: 'Olimpo Tropical', descricaoPublicacao: "HQ com roteiro de André Diniz (“Morro da favela”, “O idiota” e “7 vidas, entre outros) com desenhos de Laudo Ferreira, conta o dia a dia de Biúca, residente na favela e seus sonhos de reverter sua vida, entre eles ascender socialmente na comunidade como chefe do tráfico.", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+18', pesoPublicacao: 350, tamPublicacao: [27, 20], qtdPaginasPublicacao: 144, precoDePublicacao: 70.00, precoPorPublicacao: 52.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao11.jpg'] },
    { idPublicacao: 12, idAutorPublicacao: 2, tituloPublicacao: 'Arquivos Secretos da Segunda Guerra Mundial', descricaoPublicacao: "Luxuosa edição lançada pela Editora Draco que reúne artistas dos quadrinhos brasileiros contando várias histórias da passagem do exército brasileiro na segunda grande guerra mundial. HQ’s de drama, suspense, aventura e terror, algumas tendo fatos como inspiração, como  “Bodas de água e sal”, roteiro de Rogério Faria, desenhos de Laudo Ferreira e cores de Thaynan Lana.", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+18', pesoPublicacao: 550, tamPublicacao: [17, 24], qtdPaginasPublicacao: 260, precoDePublicacao: 80.00, precoPorPublicacao: 60.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao12.jpg'] },
    { idPublicacao: 13, idAutorPublicacao: 2, tituloPublicacao: 'Sketchbook - Laudo Ferreira', descricaoPublicacao: "A coleção Sketchbook Custom, reúne artistas gráficos, ilustradores, quadrinistas, etc. Esta edição apresenta vários trabalhos do desenhista Laudo Ferreira, desde estudos de algumas hq’s suas como Yeshuah e “Auto da barca do Inferno”, como capas, personagens, cenários, figurinos; passando por desenhos livres feitos em seus cadernos.", generoPublicacao: GenerosService.generosCadastrados[1], faixaEtariaPublicacao: '+16', pesoPublicacao: 300, tamPublicacao: [21, 28], qtdPaginasPublicacao: 64, precoDePublicacao: 50.00, precoPorPublicacao: 30.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao13.jpg'] },
    { idPublicacao: 14, idAutorPublicacao: 2, tituloPublicacao: 'Café Espacial#17', descricaoPublicacao: "Publicação de quadrinhos autorais e artes em geral. Com a participação de artistas como André Diniz, Aline Zouvi, Germana Viana, Henrique Magalhães, entre outros. Laudo Ferreira participa com a história “O Homem Ômega”, uma ficção distópica com forte crítica social, com inspiração no livro “Eu sou a lenda” de Richard Matheson e no filme de 1971 “Omega Man”, baseado no livro de Matheson.", generoPublicacao: GenerosService.generosCadastrados[4], faixaEtariaPublicacao: '+16', pesoPublicacao: 350, tamPublicacao: [17, 24], qtdPaginasPublicacao: 132, precoDePublicacao: 50.00, precoPorPublicacao: 30.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao14.jpg'] },
    { idPublicacao: 15, idAutorPublicacao: 3, tituloPublicacao: 'Kris Klaus - O Papai Noel Casca Grossa', descricaoPublicacao: "Na Noite de Natal um grupo de vampiros realiza um ritual mágico e obtêm os poderes da mítica figura do Papai Noel. Agora eles podem entrar em qualquer casa sem serem convidados e até o tempo passa diferente para eles pois esta noite especial não acabará enquanto não visitarem todas as residências do mundo. E parece que o único que pode tentar detê-los será o Bom Velhinho em pessoa. Mas quem realmente é este Papai Noel e por que tudo isto está acontecendo? Kris Klaus: Papai Noel Casca-Grossa é uma divertida história em quadrinhos de ação e aventura para todas as idades. Esta inusitada HQ mistura os gêneros de terror e infanto-juvenil. A trama é baseada na mitologia nórdica e no folclore moderno em torno da figura do Bom Velhinho. Esse é o primeiro trabalho autoral do roteirista Maurício Muniz e do desenhista Joel Lobo, ambos veteranos no mercado editorial brasileiro.", generoPublicacao: GenerosService.generosCadastrados[0], faixaEtariaPublicacao: '+10', pesoPublicacao: 150, tamPublicacao: [17, 24], qtdPaginasPublicacao: 56, precoDePublicacao: 50.00, precoPorPublicacao: 26.00, fotosPublicacao: ['../assets/publicacoes/default/publicacao15.jpg'] }
  ];
}
